PRES_NAME=docu
COMPANY_SPECIFICS=../../CompanySpecifics
MAKEFILE_DEFS=../../bin/Makefile.defs

PYTHONPOINT_TEMPLATE=-t modern
PYTHONPOINT_BACKGROUND=-g $(COMPANY_SPECIFICS)/CompanyLogo.jpg
PYTHONPOINT_BACKGROUND=
# -b or empty
BORDER=

BEAMER_TEMPLATE=-t Goettingen
BEAMER_TEMPLATE=-t default

POWERPOINT_TEMPLATE=-t $(COMPANY_SPECIFICS)/MyCompany.pot
POWERPOINT_TEMPLATE=

# -u -i
T2P_SWITCHES=


include $(MAKEFILE_DEFS)


clean: clean-base
