PRES_NAME=docu

PYTHONPOINT_TEMPLATE=-t modern
PYTHONPOINT_BACKGROUND=-g $(COMPANY_SPECIFICS)/CompanyLogo.jpg
PYTHONPOINT_BACKGROUND=
# -b or empty
BORDER=

BEAMER_TEMPLATE=-t Goettingen

POWERPOINT_TEMPLATE=-t $(COMPANY_SPECIFICS)/MyCompany.pot
POWERPOINT_TEMPLATE=

# -u -i
T2P_SWITCHES=
T2P_SWITCHES=-u


include ../../bin/Makefile.defs


clean: clean-base
